services:
  - type: web
    name: aradhyemusic
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: MONGO_DB_URI
        sync: false
      - key: OWNER_ID
        sync: false
      - key: LOG_GROUP_ID
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: HEROKU_APP_NAME
        sync: false
      - key: HEROKU_API_KEY
        sync: false
      - key: UPSTREAM_REPO
        value: https://github.com/amanraj1240/AradhyeMusic
      - key: UPSTREAM_BRANCH
        value: main
      - key: GIT_TOKEN
        sync: false
      - key: AUTO_LEAVING_ASSISTANT
        value: "True"
      - key: ASSISTANT_LEAVE_TIME
        value: "1800"
      - key: AUTO_DOWNLOADS_CLEAR
        value: "True"
      - key: DOWNLOADS_CLEAR_TIME
        value: "10800"
      - key: DURATION_LIMIT_MIN
        value: "60"
      - key: SONG_DOWNLOAD_DURATION_LIMIT
        value: "180"
      - key: PLAYLIST_FETCH_LIMIT
        value: "25"
